# Generated by Django 3.0.3 on 2020-07-29 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
        ('applicant', '0001_initial'),
        ('hradmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('applicant_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='interview', serialize=False, to='applicant.ApplicationFormModel')),
                ('schedule_date', models.DateField()),
                ('interview_timestamp', models.DateTimeField(blank=True)),
                ('result', models.CharField(choices=[('Pending', 'Pending'), ('Shortlisted', 'Shortlisted'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], default='Shortlisted', max_length=15)),
                ('interviewer_id', models.ForeignKey(limit_choices_to={'is_interviwer': True}, on_delete=django.db.models.deletion.CASCADE, to='hradmin.Employee')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.RecuirtmentModel')),
            ],
        ),
    ]
