# Generated by Django 3.0.3 on 2020-07-29 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hradmin', '0001_initial'),
        ('manager', '0001_initial'),
        ('interviewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewschedule',
            name='interview_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interviewschedule',
            name='interviewer_id',
            field=models.ForeignKey(limit_choices_to={'Designation': 'Interviwer'}, on_delete=django.db.models.deletion.CASCADE, to='hradmin.Employee'),
        ),
        migrations.AlterField(
            model_name='interviewschedule',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='manager.RecuirtmentModel'),
        ),
    ]
