# Generated by Django 3.0.3 on 2020-07-30 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hradmin', '0001_initial'),
        ('interviewer', '0002_auto_20200730_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewschedule',
            name='interviewer_id',
            field=models.ForeignKey(limit_choices_to={'Designation': 'Interviwer'}, on_delete=django.db.models.deletion.CASCADE, related_name='interviewer', to='hradmin.Employee'),
        ),
    ]
