# Generated by Django 3.0.3 on 2020-07-22 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('dep_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RecuirtmentModel',
            fields=[
                ('op_code', models.IntegerField(primary_key=True, serialize=False)),
                ('qualification', models.CharField(max_length=15)),
                ('regestration_start', models.DateField()),
                ('age_limit', models.IntegerField()),
                ('lastdate_apply', models.DateField()),
                ('no_positions', models.IntegerField()),
                ('description', models.TextField()),
                ('responsibilites', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.DepartmentModel')),
            ],
        ),
    ]
