# Generated by Django 3.0.3 on 2020-07-23 18:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('dep_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecuirtmentModel',
            fields=[
                ('op_code', models.IntegerField(primary_key=True, serialize=False)),
                ('qualification', models.CharField(max_length=255)),
                ('regestration_start', models.DateField()),
                ('experience', models.CharField(choices=[('Fresher', 'Fresher'), ('One Year', 'One Year'), ('Two Years', 'Two Years'), ('Three Years +', 'Three Years +'), ('Five Years +', 'Five Years +'), ('Ten Years +', 'Ten Years +'), ('Not Required', 'Not Required')], default='Fresher', max_length=15)),
                ('lastdate_apply', models.DateField()),
                ('no_positions', models.IntegerField()),
                ('description', models.TextField()),
                ('responsibilites', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.DepartmentModel')),
            ],
        ),
    ]
