# Generated by Django 3.0.3 on 2020-07-22 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hradmin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='employee_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=50)),
                ('Designation', models.CharField(choices=[('Manager', 'Manager'), ('HRHead', 'HRHead'), ('Interviwer', 'Interviwer'), ('Employee', 'Employee')], default='Manager', max_length=15)),
                ('contact_no', models.IntegerField(unique=True, validators=[hradmin.models.validate_contactno])),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
